### ISSUE TITLE
The project needs update, it can't work well with new gradle(3.3 or 3.2)

### ISSUE THREAD

**Issue by XinyueZ** [android/topeka#119]
The build doesn't go through when I try to build the app with newest gradle 3.3.0-alpha3.

Problems:

- Feature modules cannot use minifyEnabled in new gradle(3.2, 3.3).
- Default proguard file can only be used in base module.

I have opened #118 to let project keep the pace of new gradle, kotlin and some dependencies.

**Comment by keyboardsurfer** [comment]
Fixed in #124
