### ISSUE TITLE
Category cards in CategorySelectionActivity disappeared after coming back from QuizActivity

### ISSUE THREAD

**Issue by gejiaheng** [android/topeka#79]
On some conditions, all the visible category cards disappeared after coming back from `QuizActivity`. Like the screenshot below:

<img src="https://cloud.githubusercontent.com/assets/3777021/18982472/0e894950-8719-11e6-86b7-87702c242b71.png" width="30%" />

But you can still scroll up those left cards which are outside the screen previously.

Though not guaranteed, you may reproduce this bug as following:  
1. Click one category card to go to `QuizActivity`;
2. Press back to go back to `CategorySelectionActivity`;
3. Repeat 1 & 2 until the bug occurs.

Or, you can do the following steps to make it easier to happen:
1. Go to **Developer options** in **Settings**;
2. Change Animator duration scale to 5x or 10x;
3. Back to Topeka;
4. Click one category card to go to `QuizActivity`;
5. Press back, and don't stop, press back a few more times duration the window transition;
6. Repeat 4 & 5 until the bug occurs.

What's strange is that it can be reproduced 100% consecutively sometimes even I kill the App from the overview screen.

Phone: Nexus 6P
Android version: 7.0
Code: latest of master branch

**Comment by piotrek1543** [comment]
@gejiaheng did you noticed this issue with the latest version of app?

**Comment by keyboardsurfer** [comment]
Could not reproduce with the kotlin implementation.

**Comment by keyboardsurfer** [comment]
Seems to be reproducible with 7.x builds.

**Comment by charbgr** [comment]
Seems that `<slide>` animation causes the problem on `category_enter.xml` and `category.exit.xml`.

**Comment by gejiaheng** [comment]
@piotrek1543 I filed this bug a year ago, that can't be the latest version. 
Now I use the latest code which is kotlin implementation, I can't reproduce it any more. Hmm...

Phone: Pixel XL
Android: Oreo
